version: 2
project_name: genpasswd
before:
  hooks:
    - make clean
builds:
  - main: ./cmd/genpasswd
    binary: genpasswd
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - freebsd
      - linux
      - darwin
      - windows
    ignore:
      - goarch: 386
archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin"}}macOS
      {{- else if eq .Os "linux"}}Tux
      {{- else if eq .Os "freebsd"}}FreeBSD
      {{- else if eq .Os "windows"}}Windows
      {{- else}}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64"}}x64
      {{- else if eq .Arch "386"}}i386
      {{- else}}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
